# Generated by Django 6.0.4 on 2026-04-27 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Administration', 'Administration'), ('Cafés', 'Cafés'), ('Restaurants', 'Restaurants'), ('Services', 'Services'), ('Clubs and Organizations', 'Clubs and Organizations'), ('University Housing', 'University Housing'), ('Technology Park', 'Technology Park'), ('Technology Companies', 'Technology Companies'), ('Assembly Spaces', 'Assembly Spaces'), ('Research', 'Research'), ('Libraries', 'Libraries'), ('Metro Stations', 'Metro Stations'), ('Mosques', 'Mosques'), ('Medical Services', 'Medical Services'), ('Gym', 'Gym'), ('Sports Facilities', 'Sports Facilities'), ('available_taxi', 'Available Taxi')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('hours', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True, max_length=300)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CampusStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('date_display', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('image_name', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('facilities', 'Facilities & Infrastructure'), ('accessibility', 'Accessibility'), ('safety', 'Safety & Security'), ('technology', 'Technology & IT'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(choices=[('ENSI', 'ENSI - National School of Computer Science'), ('ISCAE', 'ISCAE - Higher Institute of Business Administration'), ('ISAMM', 'ISAMM - Higher Institute of Multimedia Arts'), ('IPSI', 'IPSI - Institute of Press and Information Sciences'), ('ISD', 'ISD - Higher Institute of Documentation'), ('ESCT', 'ESCT - Higher School of Commerce of Tunis'), ('FLAH', 'FLAH - Faculty of Letters and Humanities'), ('ESEN', 'ESEN - Higher School of Digital Economy'), ('OTHER', 'Other')], default='ENSI', max_length=10)),
                ('student_id', models.CharField(blank=True, max_length=20)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campuslocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'location')},
            },
        ),
    ]
