# Generated by Codex on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_post_file_and_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='external_file_url',
            field=models.URLField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name='post',
            name='external_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='external_file_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='external_file_url',
            field=models.URLField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name='message',
            name='external_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='external_file_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
