# Generated by Codex on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_external_attachment_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='external_file_public_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='external_file_resource_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='message',
            name='external_file_public_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='message',
            name='external_file_resource_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
