# Generated by Codex on 2026-05-22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_attachment_cloudinary_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='attachment_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
